management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLE_PROBABILITY:0.25}

logging:
  structured:
    format:
      console: ecs

commerce:
  auth:
    session-cookie-name: __Host-commerce-session
    secure-cookie: true
