spring:
  application:
    name: identity-access-service
  profiles:
    default: dev
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${IDENTITY_DB_URL}
    username: ${IDENTITY_DB_USER}
    password: ${IDENTITY_DB_PASSWORD}
    hikari:
      connection-timeout: 2000
      validation-timeout: 1000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  cloud:
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false
  mvc:
    problemdetails:
      enabled: true

commerce:
  gateway:
    routes: []

management:
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    export:
      otlp:
        enabled: false
    sampling:
      probability: ${TRACING_SAMPLE_PROBABILITY:1.0}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
server:
  port: ${IDENTITY_HTTP_PORT:8080}
  shutdown: graceful

logging:
  structured:
    format:
      console: ecs

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
