spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_HOST_PORT:55432}/catalog?connectTimeout=2&socketTimeout=2&tcpKeepAlive=true
  output:
    ansi:
      enabled: always

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
